backend:
  name: git-gateway
  branch: master
  site_domain: frabjous-cat-8b6dd9.netlify.app

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "blog"      # Used in routes, e.g., /admin/collections/blog
    label: "Blog"     # Used in the UI
    folder: "_posts/"  # The path to the folder where the documents are stored
    create: true      # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: markdown
    format: "frontmatter"

    fields: # The front matter fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"} # Custom excerpt
      - {label: "Body", name: "body", widget: "markdown"} # Mandatory body field for markdown files

  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
    - label: 'About'
      name: 'about'
      file: 'about.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }